TS_MAX_DEPTH=2
TS_SEARCH_PATHS=(~/.config ~/.dotfiles ~/projects ~/personal ~/)
TS_EXTRA_SEARCH_PATHS=()
TS_USE_TMUX_FLOAT=1
TS_FZF_DEFAULT_OPTS='
 --color=bg+:#292e42,pointer:#fbcddd,fg:#c0caf5,info:#c0caf5,hl+:#5af78e,hl:#5af78e,gutter:#1f2335,prompt:#5af78e,border:#c0caf5
'

TS_LOCAL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/tmux-sessionizer/local.conf"
[[ -r "$TS_LOCAL_CONFIG" ]] && source "$TS_LOCAL_CONFIG"
